name: Google Chat Webhook Simple

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message Google Chat
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"text\": \"🚀 New push on **${{ github.repository }}** by **${{ github.actor }}**\nCommit : ${{ github.event.head_commit.message }}\"}" \
            "${{ secrets.GOOGLE_CHAT_WEBHOOK }}"
